sm7325-common: Patch libwfdservice to resolve duplicate dependencies
Fixes:
error: module libwfdservice variant
android_arm_armv8-a_cortex-a76_static: depends on multiple
versions of the same aidl_interface:
android.media.audio.common.types-V2-cpp-source,
android.media.audio.common.types-V3-cpp-source

Change-Id: I81d6a9c2352f6ac695a95722a617f8715e67afee